version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(filename)s - %(lineno)d - %(message)s'

handlers:
  file:
    class: logging.FileHandler
    level: INFO
    formatter: detailed
    filename: logs/project.log
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard

loggers:
  root:
    handlers:
      - file
      - console
    level: INFO
    propagate: no
